The next web Clone
taiwo2/nextwebclone pull request #4
Opened 2020-12-02 15:50 UTC by taiwo2

- Follow `HTML~ semantic format
- Use CSS

2020-12-02 16:52 UTC, descholar-ceo commented
# This Pull Request is being Reviewed by [descholar-ceo](https://github.com/descholar-ceo) :eyes: :eyes: :eyes: 
## Please wait a little bit ...

2020-12-02 18:45 UTC, descholar-ceo requested changes
# Status: Change Required :vertical_traffic_light: :warning: 
## Hello @taiwo2 and @Leandro-Barretoo  :handshake: :handshake: :handshake: 
:+1: I liked that you have tried to use semantic HTML tags, that is very good, keep it up :muscle:
### :warning: However we need to make few changes to mark this project approved. See the requested change below :point_down: :point_down: :point_down: 
## Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle:
## The project

- [ ] The getting started section of your readme file has some errors, learn about those errors below :point_down:
  :X: This step `git checkout -b nextweb` is useless, since the readme file is normally displayed by default on the base branch, and it will be considered after you merge everything on the base branch, then there is no point of checkoing out another branch if a fellow programmer just wants to check if your project is cool.
  :X: This step `git pull` doesn't make sense, since you already cloned the repository on the first step, then there is no point of pulling, by cloning a repository, all of the latest changes come, so please remove that `git pull` is not needed there.
- [ ] :warning: I like the last step of running the project with `live-server`, but the problem with it is this `localhost:3000`, any almost cases the `vs-code liver-server` is opened on port `5500`, so there is no need to specify the port there unless you have a setup which enforce it, please remove the port number, it might not work with all users and that will make your repository looks unprofessional
- [ ] Your readme file doesn't have a project description, please add it, it will make your repository outstanding and professional
- [ ] And also add a live demo link to your readme file
- [ ] The navbar is distorted, font-size should be decreased to make it looks like the original page
- [ ] The top three articles section:
  - [ ] All of boxes should have a background images and make sure that they look like the original one by using same font-size, and text-colors
  - [ ] The TNW logo should look like the original one and disapear starting from screen size 1024px and downward
- [ ] The `Latest news >` sction:
  - [ ] Please reduce the space which is in-between each component and reduce the size of cards, and make sure that it's centered
  - [ ] It should be showing three cards per row on medium screens, currently it's showing four (medium screens are between 768px and 1024px)
- [ ] `Latest funding rounds on Index.co > `:
  - [ ] It doesn't follow the original page, => make sure that every card is designed the same as the original
  - [ ] It should show for cards on large screens, and three card on medium screen, and and one card on mobile screen
  - [ ] Each card should have a cover image and title placed below the image
   - [ ] on mobile versions each card should have a cover image on the left side and title on the right side of the row
- [ ] The categories (`Hard Fork >`, Apps, Gear, Tech, etc) section:
  - [ ] Should be designed in such a way that it contains a header with the section name
  - [ ] Make sure that they look like the original page
- [ ] You are missing the `Latest deals section` please add it
- [ ] The footer touches each sides (left side and right side)
- [ ] And make sure that the footer is similar to the original one with the background colors and font-sizes

## The codes

- [ ] You have used `SVG` in your HTML file, that is okay, but it is not good since it has some side effect such difficulty of your code readability, a big chunk of crap right in the document, and inability to cache. Please remove all SVG images from html file and put them in a separate folder and call them as images
- [ ] You have used some ID selectors in your CSS file => that is a bad practice, you should use class instead
- [ ] You have a lot of CSS files, that is likely to make you repeating yourself, and also it reduce your code maintaimability. I am not against using more than one CSS file but that depends on the project size, since this project is just as small as a one page, I don't see a reason to use a lot of CSS files which sounds like almost every section has its styling file. For example: you have these files: `latest.css, new-latest.css, categories.css, ...` You can't write a separate file just for each section, this might give you headache when it comes to debugging or updating something. Please all of files which are styling some specific sections, merge them into one file and make sure that you don't repeat yourself
  - [ ] You have some linting errors please fix them
  - [ ] Add more description on this Pull request, you should actually explain what you have done on this Pull request in summary
  - [ ] It would be very nice if you add a screenshot of your clone in the readme file

If anything seems to be unclear to you, comment on this Pull Request and mention me as [@descholar-ceo](https://github.com/descholar-ceo)

 | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)

2020-12-02 18:45 UTC, descholar-ceo commented on index.html
> +    <!-- <link rel="stylesheet" href="stylesheet/style-gitreset.css"> -->
Remove this line of commented code

2020-12-02 18:45 UTC, descholar-ceo commented on index.html
> +            </div> -->
This commented code is not needed to be left here

2020-12-03 15:29 UTC, jubaan requested changes
# Status: Changes Required :recycle: 

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [ ] The README has a comment that comes from a merge conflict, please remove it
![image](https://user-images.githubusercontent.com/25774518/101043847-5b418180-3544-11eb-85fd-a9daf884e915.png)

- [ ] The link to the live preview should be an Actual link. To accomplish that use this syntax `[Text link](URL)`. Example: [@jubaan](https://www.github.com/jubaan)

- [ ] The README file has some conflicts please work on them.
![image](https://user-images.githubusercontent.com/25774518/101044239-bd9a8200-3544-11eb-8c99-2336189b36c9.png)

- [ ] The linters are not set up correctly, they are not checking errors. It should appear stylelinter and webhint.
![image](https://user-images.githubusercontent.com/25774518/101044389-e753a900-3544-11eb-9663-147c06ee8d5b.png)

- [ ] Remove from repository the files that are not needed.
![image](https://user-images.githubusercontent.com/25774518/101044826-6ba62c00-3545-11eb-8f87-b348e10eeb9e.png)
![image](https://user-images.githubusercontent.com/25774518/101044918-837db000-3545-11eb-8d97-ab52f4c1f91c.png)

- [ ] The live preview link isn't working. It only shows a blank page.

- [ ] The index HTML has no code in it.

- [ ]  **Your readme file doesn't have a project description, please add it, it will make your repository outstanding and professional**

- [ ]  **And also add a live demo link to your readme file**

- [ ] Some changes that you have made previously have made the project to stop working as expected. The website is not displaying. index.html doesn't contain any code, the live preview link shows a white space, is not displaying anything this is because of the lack of code in the index.html

There are still some pending issues to be validated:
> * [ ]  The navbar is distorted, font-size should be decreased to make it looks like the original page
> * [ ]  The top three articles section:
>   
>   * [ ]  All of boxes should have a background images and make sure that they look like the original one by using same font-size, and text-colors
>   * [ ]  The TNW logo should look like the original one and disapear starting from screen size 1024px and downward
> * [ ]  The `Latest news >` sction:
>   
>   * [ ]  Please reduce the space which is in-between each component and reduce the size of cards, and make sure that it's centered
>   * [ ]  It should be showing three cards per row on medium screens, currently it's showing four (medium screens are between 768px and 1024px)
> * [ ]  `Latest funding rounds on Index.co > `:
>   
>   * [ ]  It doesn't follow the original page, => make sure that every card is designed the same as the original
>   * [ ]  It should show for cards on large screens, and three card on medium screen, and and one card on mobile screen
>   * [ ]  Each card should have a cover image and title placed below the image
>   * [ ]  on mobile versions each card should have a cover image on the left side and title on the right side of the row
> * [ ]  The categories (`Hard Fork >`, Apps, Gear, Tech, etc) section:
>   
>   * [ ]  Should be designed in such a way that it contains a header with the section name
>   * [ ]  Make sure that they look like the original page
> * [ ]  You are missing the `Latest deals section` please add it
> * [ ]  The footer touches each sides (left side and right side)
> * [ ]  And make sure that the footer is similar to the original one with the background colors and font-sizes
> 
> ## The codes
> * [ ]  You have used `SVG` in your HTML file, that is okay, but it is not good since it has some side effect such difficulty of your code readability, a big chunk of crap right in the document, and inability to cache. Please remove all SVG images from html file and put them in a separate folder and call them as images

- [ ]  **You have used some ID selectors in your CSS file => that is a bad practice, you should use class instead**

> * [ ]  You have a lot of CSS files, that is likely to make you repeating yourself, and also it reduce your code maintaimability. I am not against using more than one CSS file but that depends on the project size, since this project is just as small as a one page, I don't see a reason to use a lot of CSS files which sounds like almost every section has its styling file. For example: you have these files: `latest.css, new-latest.css, categories.css, ...` You can't write a separate file just for each section, this might give you headache when it comes to debugging or updating something. Please all of files which are styling some specific sections, merge them into one file and make sure that you don't repeat yourself
>   
>   * [ ]  You have some linting errors please fix them

- [ ]  **Add more description on this Pull request, you should actually explain what you have done on this Pull request in summary**

- [ ]  **It would be very nice if you add a screenshot of your clone in the readme file**

**COMMENTS: Before submitting for a re-review, check that all you project is working. To ensure this only push to the repository code that is needed and that you have personally check is working. Everything else leave it out of the repo. This way it would look more professional, tidy, and most of all you will ensure is working.**

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

2020-12-03 17:28 UTC, descholar-ceo requested changes
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @taiwo2 and @Leandro-Barretoo  :handshake: :handshake: :handshake: 
:+1: This is good to make it this far, your clone looks like the original page and it is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.
:+1: It's so amazing that you have done a great progress, your project is almost there
### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
## Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [ ] The clone now almost looks like the original page, the only remaining issue is collors and font-sizes. Your font-sizes are somehow bigger than the original ones, that is causing your clone to look strange, please try to adjust colors and font-sizes to make your clone good.
### Examples
#### 1. Navbars
| Your clone | Original page |
| --- | --- |
| ![Screenshot from 2020-12-03 19-12-53](https://user-images.githubusercontent.com/56886064/101063580-a0dd6900-359b-11eb-8892-62e47b017892.png) | ![Screenshot from 2020-12-03 19-13-55](https://user-images.githubusercontent.com/56886064/101063658-b6eb2980-359b-11eb-955b-2794acc7ff52.png) |
:point_right: Could you see the difference :question: :question: :question: 

#### 2. `Latest funding rounds on Index.co ` section, it is even distorted on large screens, the three options should be aligned on the leftmost side of the screen

| Your clone | Original page |
| --- | --- |
| ![Screenshot from 2020-12-03 19-18-42](https://user-images.githubusercontent.com/56886064/101064185-62947980-359c-11eb-8a1c-ed18e42850f3.png)| ![Screenshot from 2020-12-03 19-15-54](https://user-images.githubusercontent.com/56886064/101064090-45f84180-359c-11eb-9b69-a2449d21f04d.png)|
:point_right: Could you see the difference :question: :question: :question: 

#### 3. `Categories (Apps, Gear, Tech, etc) section`

| Your clone | Original page |
| --- | --- |
| ![Screenshot from 2020-12-03 19-23-29](https://user-images.githubusercontent.com/56886064/101064803-0da53300-359d-11eb-9a68-153ce5966734.png)| ![Screenshot from 2020-12-03 19-22-22](https://user-images.githubusercontent.com/56886064/101064641-e8182980-359c-11eb-8b14-3027b5ad4b25.png)|

:point_right: Could you see the difference :question: :question: :question: 

#### 4. Footer

| Your clone | Original page |
| --- | --- |
| ![Screenshot from 2020-12-03 19-25-52](https://user-images.githubusercontent.com/56886064/101065102-6aa0e900-359d-11eb-90f4-66a61463cde4.png)|![Screenshot from 2020-12-03 19-26-43](https://user-images.githubusercontent.com/56886064/101065174-81dfd680-359d-11eb-8fc3-f865de23ac78.png)|

:point_right: Could you see the difference :question: :question: :question: 


- [ ] The pull request description is not yet worked on
- [ ] It's very good to have worked on readme file project description, but there some typos, instead of writing `The New Web` should be `thenextweb`
- [ ] The link to the live preview should be an Actual link. To accomplish that use this syntax [Text link](URL). Example: [@descholar-ceo](https://github.com/descholar-ce)
- [ ] You have used SVG in your HTML file, that is okay, but it is not good since it has some side effect such difficulty of your code readability, a big chunk of crap right in the document, and inability to cache. Please remove all SVG images from html file and put them in a separate folder and call them as images
- [ ] The footer should have two different colors, the one above and the other one below, yours has only one color, please fix that
- [ ] You have used some ID selectors in your CSS file => that is a bad practice, you should use class instead
- [ ] It would be very nice if you add a screenshot of your clone in the readme file
- [ ] You still have linters issues, please fix them

___
_If anything seems to be unclear to you, comment on this Pull request and mention me as [@descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

 | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

Re-reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)

2020-12-04 18:08 UTC, abredi requested changes
### Status: Require changes 🌳 ♲
Hi @taiwo2 and @Leandro-Barretoo, I am  [Abdulaziz Redi Ali](https://azizali.ml/), your TSE for this PR.  👏👏   I appreciate your hard work in replicating thenextweb.com. You already fulfilled most of the requirements, kindly fix the following issues. 

[REQUIRED]

_Click the image to view it in full._

- [ ] Fix text overlay on the navigation. Use a higher `z-index` for the navigation.
- [ ] Fix the font family and font styles 
- [ ] The Categories (Apps, Gear, Tech, etc) row should have two articles per row

| Your Copy | Source |
| :---: | :---: |
|<img width="1045" alt="Screen Shot 2020-12-04 at 8 50 09 PM" src="https://user-images.githubusercontent.com/38358081/101198207-27fe1000-3674-11eb-92e3-1e5176953d55.png">|<img width="1045" alt="Screen Shot 2020-12-04 at 9 06 43 PM" src="https://user-images.githubusercontent.com/38358081/101198515-a064d100-3674-11eb-9e6c-e39afe6fd4ef.png">|
|<img width="1045" alt="Screen Shot 2020-12-04 at 8 52 01 PM" src="https://user-images.githubusercontent.com/38358081/101198247-377d5900-3674-11eb-8fab-11b4a2c860a4.png">|

Once you fix the issues, kindly submit another code review. ♲

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

2020-12-04 19:20 UTC, abredi requested changes
### Status: Require changes 🌳 ♲
Hi @, I am  [Abdulaziz Redi Ali](https://azizali.ml/), your TSE for this PR.  👏👏   I appreciate your hard work in replicating thenextweb.com. Kindly fix the issues stated in the previous review. 


![breakpoints_requirement](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/responsive_design/breakpoints_requirement.png)

Once you fix the issues, kindly submit another code review. ♲

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

2020-12-04 19:38 UTC, arslanbisharat approved these changes

2021-01-18 08:12 UTC, merged